//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCezalar
    {
        public int CezaID { get; set; }
        public Nullable<int> Uye { get; set; }
        public Nullable<int> Hareket { get; set; }
        public Nullable<System.DateTime> Baslangıc { get; set; }
        public Nullable<System.DateTime> Bitis { get; set; }
        public Nullable<decimal> ParaCeza { get; set; }
    
        public virtual TblHareketler TblHareketler { get; set; }
        public virtual TblUyeler TblUyeler { get; set; }
    }
}
