//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHareketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblHareketler()
        {
            this.TblCezalar = new HashSet<TblCezalar>();
        }
    
        public int HareketID { get; set; }
        public Nullable<int> AlinanKitap { get; set; }
        public Nullable<int> Uye { get; set; }
        public Nullable<int> Personel { get; set; }
        public Nullable<System.DateTime> AlısTarih { get; set; }
        public Nullable<System.DateTime> IadeTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblCezalar> TblCezalar { get; set; }
        public virtual TblKitap TblKitap { get; set; }
        public virtual TblUyeler TblUyeler { get; set; }
    }
}
